name: Node CI/CD Pipeline

on:
  push:
    branches:
      - master  # Akan berjalan setiap kali ada push ke branch master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulasi Build
        run: |
          echo "Di sini Build Docker"
          echo "Build Successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Menunggu job 'build' selesai dulu
    steps:
      - name: Simulasi Deploy
        run: |
          echo "Di sini Proses Deploy"
          echo "Deploy Successfully!"